name: "Build and Deploy"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    inputs:
      godot_version:
        description: "Godot Version"
        required: true
        type: string
        default: "4.3"
      export_platform:
        description: "Export Platform - all|windows|linux|web|macos"
        required: true
        type: string
        default: "all"
      export_folder:
        description: "Export Folder - Repository Path"
        required: true
        type: string
        default: "."
      export_name:
        description: "Export Name"
        required: true
        type: string
        default: viking-funeral
      itch_io:
        description: "Itch.io Build"
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      godot_version:
        description: "Godot Version"
        required: true
        default: "4.3"
      export_platform:
        description: "Export Platform - all|windows|linux|web|macos"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - windows
          - linux
          - web
          - macos
      export_folder:
        description: "Export Folder - Repository Path"
        required: true
        default: "."
      export_name:
        description: "Export Name"
        required: true
        default: viking-funeral
      itch_io:
        description: "Itch.io Build"
        required: false
        default: "false"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GODOT_VERSION: ${{ github.event.inputs.godot_version || '4.3' }}
  EXPORT_PLATFORM: ${{ github.event.inputs.export_platform || 'all' }}
  EXPORT_FOLDER: ${{ github.event.inputs.export_folder || '.' }}
  EXPORT_NAME: ${{ github.event.inputs.export_name || 'viking-funeral' }}
  ITCH_IO: ${{ github.event.inputs.itch_io || 'false' }}

jobs:
  export_windows:
    name: Windows Export
    runs-on: ubuntu-24.04
    if: ${{ github.event.inputs.export_platform == 'windows' || github.event.inputs.export_platform == 'all' || github.event_name == 'pull_request' }}
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/windows
          godot -v --headless --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: ${{ env.EXPORT_FOLDER }}/build/windows
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/windows
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == 'true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip

  export_linux:
    name: Linux Export
    runs-on: ubuntu-24.04
    if: ${{ github.event.inputs.export_platform == 'linux' || github.event.inputs.export_platform == 'all' || github.event_name == 'pull_request' }}
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/linux
          godot -v --headless --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: ${{ env.EXPORT_FOLDER }}/build/linux
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/linux
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == 'true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip

  export_web:
    name: Web Export
    runs-on: ubuntu-24.04
    if: ${{ github.event.inputs.export_platform == 'web' || github.event.inputs.export_platform == 'all' || github.event_name == 'pull_request' }}
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          mv -v /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/
      - name: Web Build
        run: |
          mkdir -v -p builds/web
          godot -v --headless --export-release "Web" ./builds/web/index.html
      - name: Add COI Service Worker
        run: |
          wget https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.min.js -O ./builds/web/coi-serviceworker.min.js
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.EXPORT_FOLDER }}/builds/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/builds/web
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == 'true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: HTML
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip

  export_mac:
    name: Mac Export
    runs-on: ubuntu-24.04
    if: ${{ github.event.inputs.export_platform == 'macos' || github.event.inputs.export_platform == 'all' || github.event_name == 'pull_request' }}
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/mac
          godot -v --headless --export-release "macOS" ./build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mac
          path: ${{ env.EXPORT_FOLDER }}/build/mac
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/mac
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == 'true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip
